---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Start Locust in worker mode
      command: locust -f edgenative.py --worker --master-host={master}
      async: 100000000 
      poll: 0
